// src/components/Tools.jsx
import React from 'react';

export default function Tools() {
  const col = 'grid grid-cols-2 gap-6';
  const imgClass = 'w-20 mx-auto transform transition-transform duration-300 hover:scale-110';

  return (
    <div className="w-full px-6 sm:px-12 md:px-20 min-h-screen bg-gray-900">
      <div className="text-center">
        <h1
          id="tools"
          className="pt-32 pb-10 text-3xl md:text-4xl font-bold text-white"
        >
          <span className="inline-block border-b-4 border-blue-400 pb-5">
            Tech Stack
          </span>
        </h1>
      </div>
      <div className="grid md:grid-cols-3 gap-10 text-center text-white">
        <div>
          <h3 className="text-lg font-semibold my-3">FRONT END</h3>
          <div className={col}>
            <img src="/images/tools/html.svg" className={imgClass} alt="HTML" />
            <img src="/images/tools/css.svg" className={imgClass} alt="CSS" />
            <img src="/images/tools/javascript.svg" className={imgClass} alt="JavaScript" />
            <img src="/images/tools/react.svg" className={imgClass} alt="React" />
          </div>
        </div>
        <div>
          <h3 className="text-lg font-semibold my-3">BACK END</h3>
          <div className={col}>
            <img src="/images/tools/nodejs.svg" className={imgClass} alt="Node.js" />
            <img src="/images/tools/expressjs.svg" className={imgClass} alt="Express.js" />
            <img src="/images/tools/mongodb.svg" className={imgClass} alt="MongoDB" />
            <img src="/images/tools/heroku.svg" className={imgClass} alt="Heroku" />
          </div>
        </div>
        <div>
          <h3 className="text-lg font-semibold my-3">TOOLS</h3>
          <div className={col}>
            <img src="/images/tools/git.svg" className={imgClass} alt="Git" />
            <img src="/images/tools/postman.svg" className={imgClass} alt="Postman" />
            <img src="/images/tools/sublime.svg" className={imgClass} alt="Sublime Text" />
            <img src="/images/tools/js.svg" className={imgClass} alt="JavaScript" />
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/Tools.vue
<template>
	<!-- tools -->
	
	<div class="row mb-5 flex-column">
	<h1 class="mt-5 py-3 text-center" id="tools" >Tech Stack</h1>
	    
	    <div class="row text-center justify-content-center px-5 py-3 tools-img">

	        <div class="col-md-3 col-lg-2 mx-4 my-3">
	            <h3 class="my-3 text-center">FRONT END</h3>

	            <div class="row justify-content-center tools-img gx-5">
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/html.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/css.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/bootstrap.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/js.svg" class="img-fluid">
	                </div>
	            </div>

	        </div>


	        <div class="col-md-3 col-lg-2 mx-4 my-3">
	            <h3 class="my-3 text-center">MERN</h3>
	            <div class="row tools-img gx-5">
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/mongodb.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/expressjs.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/react.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/nodejs.svg" class="img-fluid">
	                </div>
	            </div>
	        </div>


	        <div class="col-md-3 col-lg-2 mx-4 my-3">
	            <h3 class="my-3 text-center">OTHER TOOLS</h3>
	            <div class="row tools-img gx-5">

	                <div class="col-6 tools-img">
	                    <img src="/images/tools/heroku.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/git.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/postman.svg" class="img-fluid">
	                </div>
	                <div class="col-6 tools-img">
	                    <img src="/images/tools/sublime.svg" class="img-fluid">
	                </div>
	            </div>
	        </div>


	    </div>
	</div>
</template>
