// src/csp1.jsx
import React from 'react'
import Navbar from './components/Navbar'
import About from './components/About'
import Projects from './components/Projects'
import Tools from './components/Tools'
import Contact from './components/Contact'
import FooterComponent from './components/FooterComponent'

export default function App() {
  return (
    <div>
      <Navbar />
      <main>
        <About />
        
        <Projects />
        <Tools />
        <Contact />
      </main>
      <FooterComponent />
    </div>
  )
}

// src/csp1.vue
<script setup>
  import Navbar from './components/Navbar.vue';
  import About from './components/About.vue';
  import Projects from './components/Projects.vue';
  import Tools from './components/Tools.vue';
  import Contact from './components/Contact.vue';
  import FooterComponent from './components/FooterComponent.vue';
</script>

<template>
  
  <Navbar />
  <div class="container-fluid">
    <About />
    <Projects />
    <Tools />
    <Contact />
  </div>
  <FooterComponent />


</template>
<style></style>
